/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.Formatacao;
import apoio.GeraLicenca;
import apoio.RSAcriptografia;
import apoio.VerificadorCampos;
import dao.GenericDAO;
import dao.ProdutoDAO;
import entidade.Licenca;
import entidade.Produto;
import java.awt.Label;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import java.io.PrintWriter;
import java.io.*;
import java.nio.*;
import java.nio.channels.*;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Morgana
 */
public class DlgLicenca extends javax.swing.JDialog {

    /**
     * Creates new form DlgClientes
     */
    public DlgLicenca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public Label getJlTitulobMensagem() {
        return this.jlbTituloMensagem;
    }

    public Label getJlbMensagem() {
        return this.jlbMensagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelecionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlCadastro = new javax.swing.JPanel();
        pnlLicenca = new javax.swing.JPanel();
        jlbTituloMensagem = new java.awt.Label();
        jlbMensagem = new java.awt.Label();
        tfdCaminho = new javax.swing.JTextField();
        btnSelecionarLicenca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Licença");
        setResizable(false);

        btnSelecionar.setText("Ativar");
        btnSelecionar.setName("btnSelecionar"); // NOI18N
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnlCadastro.setName("pnlCadastro"); // NOI18N

        pnlLicenca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Licença do Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jlbTituloMensagem.setAlignment(java.awt.Label.CENTER);
        jlbTituloMensagem.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlbTituloMensagem.setForeground(new java.awt.Color(255, 0, 0));
        jlbTituloMensagem.setName(""); // NOI18N
        jlbTituloMensagem.setText("ATENÇÃO");

        jlbMensagem.setAlignment(java.awt.Label.CENTER);
        jlbMensagem.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlbMensagem.setForeground(new java.awt.Color(255, 0, 0));
        jlbMensagem.setName(""); // NOI18N
        jlbMensagem.setText("ATENÇÃO");

        javax.swing.GroupLayout pnlLicencaLayout = new javax.swing.GroupLayout(pnlLicenca);
        pnlLicenca.setLayout(pnlLicencaLayout);
        pnlLicencaLayout.setHorizontalGroup(
            pnlLicencaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLicencaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlLicencaLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jlbTituloMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLicencaLayout.setVerticalGroup(
            pnlLicencaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLicencaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTituloMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tfdCaminho.setEditable(false);

        btnSelecionarLicenca.setText("Selecionar nova licença");
        btnSelecionarLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarLicencaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLicenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addComponent(btnSelecionarLicenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionarLicenca)
                    .addComponent(tfdCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLicenca.getAccessibleContext().setAccessibleName("LICENÇA DO SISTEMA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed

        JComponent[] components = new JComponent[]{tfdCaminho};
        VerificadorCampos verifier = new VerificadorCampos(components);
        
        
        if (!verifier.validaCampos()) {
            return;
        }


        try {
            File fIn = new File(tfdCaminho.getText());
            File fOut = new File("smartagro.licenca");
            FileInputStream fis = new FileInputStream(fIn);
            FileOutputStream fos = new FileOutputStream(fOut);
            FileChannel fcIn = fis.getChannel();
            FileChannel fcOut = fos.getChannel();
            fcOut.transferFrom(fcIn, 0, fIn.length());
            fos.close();
            fis.close();
            Licenca l = new Licenca();
            l = GeraLicenca.pegaLicenca();
            FrmPrincipal.setMensagemLicenca("Licença válida até: "+Formatacao.DataDMA(l.getValidade()));
        } catch (Exception e) {
            e.printStackTrace();
        }

        String verificaLicenca = GeraLicenca.verificaLicenca();
        if (verificaLicenca.contains("Erro") || verificaLicenca.contains("expirada") || verificaLicenca.contains("Falha")) {
            JOptionPane.showMessageDialog(null, verificaLicenca + ". Software será fechado.", "Licença", JOptionPane.OK_OPTION);
            System.exit(0);
        } else if (verificaLicenca.contains("Resta(m)") || verificaLicenca.contains("Último")) {
            JOptionPane.showMessageDialog(null, verificaLicenca, "Licença", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Software licenciado com sucesso!", "Licença", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }

        this.dispose();
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnSelecionarLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarLicencaActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        
        int result = fileChooser.showOpenDialog(this);
          //fileChooser.setFileFilter(new FileNameExtensionFilter("licence"));
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            tfdCaminho.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_btnSelecionarLicencaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgLicenca dialog = new DlgLicenca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnSelecionarLicenca;
    private java.awt.Label jlbMensagem;
    private java.awt.Label jlbTituloMensagem;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlLicenca;
    private javax.swing.JTextField tfdCaminho;
    // End of variables declaration//GEN-END:variables
}
