/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.*;
import java.util.ArrayList;
import dao.GenericDAO;
import entidade.Formapagamento;
import entidade.Venda;
import entidade.Itemvenda;
import entidade.ItemvendaPK;
import entidade.Produto;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JComponent;
import org.apache.log4j.Logger;
import smartagro.VerificaPermissao;

/**
 *
 * @author Morgana
 */
public class IfrmVenda extends javax.swing.JInternalFrame {

    private GenericDAO<Venda> dao;
    private Venda venda;
    private Produto produto;
    private jtmItensVenda modelItens;
    private jtmVenda modelVenda;
    private ArrayList<Venda> vendas;

    private DlgClientes dlgClientes;
    private DlgColaboradores dlgColaboradores;
    private DlgProdutos dlgProdutos;

    private boolean editando = false;
    private boolean editandoItem = false;

    private static final Logger logger = Logger.getLogger(IfrmVenda.class);

    /**
     * Creates new form IfrmVenda
     */
    public IfrmVenda(int aba) {
        initComponents();
        
        // Abre na aba passada por parametro
        tabAbas.setSelectedIndex(aba);

        // Preenche a tabela de itens com as colunas corretas
        modelItens = new jtmItensVenda(new ArrayList<Itemvenda>());
        tblItens.setModel(modelItens);

        // Preenche a tabela de consulta com as colunas corretas
        vendas = new ArrayList<Venda>();
        modelVenda = new jtmVenda(vendas);
        tblVendas.setModel(modelVenda);

        dlgClientes = new DlgClientes(null, true);
        dlgColaboradores = new DlgColaboradores(null, true);
        dlgProdutos = new DlgProdutos(null, true);
        
        popularComboStatus();
        
        new VerificaPermissao(this.getClass().getSimpleName(), this.getContentPane());

        focus();
    }

    private void focus() {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                tfdCliente.requestFocusInWindow();
            }
        });
    }

    private void popularComboStatus() {
        cbmStatus.removeAllItems();
        cbmStatus.addItem("Selecione");

        for (Object st : new Venda().getTodosStatus()) {
            cbmStatus.addItem(st.toString());
        }

        cbmStatus.setSelectedIndex(0);
    }

    private void limparPainelCadastro() {
        LimpaCampos.limparCampos(pnlCabecalho);
        LimpaCampos.limparCampos(pnlItens);
        LimpaCampos.limparCampos(pnlComplemento);

        this.modelItens = new jtmItensVenda(new ArrayList<Itemvenda>());
        tblItens.setModel(this.modelItens);

        atualizaSubtotal();
        atualizaTotal();
    }

    private boolean getEditandoVenda() {
        return editando;
    }

    private void setEditandoVenda(boolean editando) {
        this.editando = editando;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPaga = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVendasE = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        tabAbas = new javax.swing.JTabbedPane();
        pnlCadastro = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfdVenda = new javax.swing.JTextField();
        tfdCliente = new javax.swing.JTextField();
        btnZoomCliente = new javax.swing.JButton();
        btnZoomVendedor = new javax.swing.JButton();
        tfdVendedor = new javax.swing.JTextField();
        ffdData = new javax.swing.JFormattedTextField();
        cbmStatus = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        rbtPagaSim = new javax.swing.JRadioButton();
        rbtPagaNao = new javax.swing.JRadioButton();
        pnlItens = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfdProduto = new javax.swing.JTextField();
        btnZoom = new javax.swing.JButton();
        tfdPrecoUn = new apoio.MoedaFormatada();
        tfdDescontoUn = new apoio.MoedaFormatada();
        tfdSubtotal = new apoio.MoedaFormatada();
        ffdQuantidade = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        tfdCodigoPro = new javax.swing.JTextField();
        pnlComplemento = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfdDesconto = new apoio.MoedaFormatada();
        tfdDescrDesc = new javax.swing.JTextField();
        tfdObservacao = new javax.swing.JTextField();
        brnPagamento = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblTotalLiquido = new javax.swing.JLabel();
        pnlConsulta = new javax.swing.JPanel();
        btnPesquisar = new javax.swing.JButton();
        jYTableScrollPane1 = new de.javasoft.swing.JYTableScrollPane();
        tblVendas = new de.javasoft.swing.JYTable();

        tblVendasE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tblVendasE);

        setClosable(true);
        setIconifiable(true);
        setTitle("Venda");
        setName("IfrmVenda"); // NOI18N

        btnEditar.setText("Editar");
        btnEditar.setName("btnEditar"); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setName("btnExcluir"); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tabAbas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabAbasStateChanged(evt);
            }
        });
        tabAbas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tabAbasFocusLost(evt);
            }
        });

        pnlCadastro.setName("pnlCadastro"); // NOI18N

        pnlCabecalho.setBorder(javax.swing.BorderFactory.createTitledBorder("Cabeçalho"));

        jLabel2.setText("Venda");

        jLabel3.setText("Cliente *");

        jLabel4.setText("Vendedor *");

        jLabel5.setText("Data emissão");

        jLabel6.setText("Status");

        tfdVenda.setEditable(false);

        tfdCliente.setEditable(false);

        btnZoomCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zoom.png"))); // NOI18N
        btnZoomCliente.setToolTipText("Pesquisar");
        btnZoomCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnZoomCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomClienteActionPerformed(evt);
            }
        });

        btnZoomVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zoom.png"))); // NOI18N
        btnZoomVendedor.setToolTipText("Pesquisar");
        btnZoomVendedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnZoomVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomVendedorActionPerformed(evt);
            }
        });

        tfdVendedor.setEditable(false);

        ffdData.setEditable(false);

        cbmStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Paga");

        btgPaga.add(rbtPagaSim);
        rbtPagaSim.setText("Sim");
        rbtPagaSim.setEnabled(false);

        btgPaga.add(rbtPagaNao);
        rbtPagaNao.setText("Não");
        rbtPagaNao.setEnabled(false);

        javax.swing.GroupLayout pnlCabecalhoLayout = new javax.swing.GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                        .addComponent(tfdCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZoomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZoomVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                        .addComponent(tfdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ffdData, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbmStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtPagaSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtPagaNao)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlCabecalhoLayout.setVerticalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(tfdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ffdData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(rbtPagaSim)
                    .addComponent(rbtPagaNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZoomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(btnZoomVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlItens.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens"));

        jLabel7.setText("Produto *");

        jLabel8.setText("Desconto");

        jLabel9.setText("Quantidade *");

        jLabel10.setText("Subtotal");

        jLabel11.setText("Preço *");

        tfdProduto.setEditable(false);

        btnZoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zoom.png"))); // NOI18N
        btnZoom.setToolTipText("Pesquisar");
        btnZoom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomActionPerformed(evt);
            }
        });

        tfdPrecoUn.setEditable(false);
        tfdPrecoUn.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfdDescontoUn.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfdDescontoUn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdDescontoUnFocusLost(evt);
            }
        });

        tfdSubtotal.setEditable(false);
        tfdSubtotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        ffdQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ffdQuantidadeFocusLost(evt);
            }
        });

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblItens);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        tfdCodigoPro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdCodigoProFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlItensLayout = new javax.swing.GroupLayout(pnlItens);
        pnlItens.setLayout(pnlItensLayout);
        pnlItensLayout.setHorizontalGroup(
            pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItensLayout.createSequentialGroup()
                        .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfdPrecoUn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdCodigoPro, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlItensLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ffdQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdDescontoUn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItensLayout.createSequentialGroup()
                                .addComponent(tfdProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemover))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        pnlItensLayout.setVerticalGroup(
            pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensLayout.createSequentialGroup()
                .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tfdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfdCodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfdPrecoUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(tfdDescontoUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ffdQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfdSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnRemover)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlComplemento.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados complementares"));

        jLabel12.setText("Desconto");

        jLabel13.setText("Descrição desconto");

        jLabel14.setText("Observação");

        tfdDesconto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfdDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdDescontoFocusLost(evt);
            }
        });

        brnPagamento.setText("Condição de pagamento");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("Total");

        lblTotalLiquido.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTotalLiquido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalLiquido.setText("Total Líquido");

        javax.swing.GroupLayout pnlComplementoLayout = new javax.swing.GroupLayout(pnlComplemento);
        pnlComplemento.setLayout(pnlComplementoLayout);
        pnlComplementoLayout.setHorizontalGroup(
            pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComplementoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlComplementoLayout.createSequentialGroup()
                        .addComponent(tfdDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdDescrDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfdObservacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brnPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalLiquido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlComplementoLayout.setVerticalGroup(
            pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComplementoLayout.createSequentialGroup()
                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(brnPagamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlComplementoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlComplementoLayout.createSequentialGroup()
                                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(tfdDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdDescrDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(tfdObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlComplementoLayout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTotalLiquido)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCabecalho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlComplemento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabAbas.addTab("Cadastro", pnlCadastro);

        pnlConsulta.setName("pnlConsulta"); // NOI18N

        btnPesquisar.setText("Carregas dados");
        btnPesquisar.setName("btnPesquisar"); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jYTableScrollPane1.setViewportView(tblVendas);

        javax.swing.GroupLayout pnlConsultaLayout = new javax.swing.GroupLayout(pnlConsulta);
        pnlConsulta.setLayout(pnlConsultaLayout);
        pnlConsultaLayout.setHorizontalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultaLayout.createSequentialGroup()
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jYTableScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlConsultaLayout.setVerticalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jYTableScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabAbas.addTab("Consulta", pnlConsulta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addContainerGap())
            .addComponent(tabAbas)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("Venda");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabAbasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabAbasStateChanged
        HabilitaCampos.controlaBotoes(evt, btnSalvar, btnEditar, btnExcluir);
    }//GEN-LAST:event_tabAbasStateChanged

    private void tabAbasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabAbasFocusLost
        HabilitaCampos.controlaPainelCadastro(evt, editando);
    }//GEN-LAST:event_tabAbasFocusLost

    private void btnZoomClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomClienteActionPerformed
        dlgClientes.setVisible(true);
        if (dlgClientes.getCliente() != null) {
            tfdCliente.setText(dlgClientes.getClienteToString());
        }
    }//GEN-LAST:event_btnZoomClienteActionPerformed

    private void btnZoomVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomVendedorActionPerformed
        dlgColaboradores.setVisible(true);
        if (dlgColaboradores.getColaborador() != null) {
            tfdVendedor.setText(dlgColaboradores.getColaboradorToString());
        }
    }//GEN-LAST:event_btnZoomVendedorActionPerformed

    private void btnZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomActionPerformed
        dlgProdutos.setVisible(true);
        if (dlgProdutos.getProduto() != null) {
            if (dlgProdutos.getProduto().getCodigo() != null) {
                tfdCodigoPro.setText(dlgProdutos.getProduto().getCodigo());
            }
            tfdProduto.setText(dlgProdutos.getProduto().getDescricao());

            // Atualiza o produto selecionado pelo usuário
            this.produto = dlgProdutos.getProduto();
            atualizaInputProduto(this.produto);
        }
    }//GEN-LAST:event_btnZoomActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        Itemvenda item = new Itemvenda();
        ItemvendaPK pk = new ItemvendaPK();

        if (getEditandoItem()) {
            item = retornaItemSelecionado();
            pk = item.getItemvendaPK();
        }

        pk.setProduto(this.produto);

        BigDecimal qtd = Formatacao.converteStringParaBigDecimal(ffdQuantidade.getText());
        item.setDesconto(tfdDescontoUn.getValue().setScale(2));
        item.setQuantidade(qtd);
        item.setValor(tfdPrecoUn.getValue().setScale(2));
        item.setValortotal(tfdSubtotal.getValue().setScale(2));
        item.setVenda(venda);
        item.setItemvendaPK(pk);

        // Valida o produto
        if (!validaItem(item) || !validaItens()) {
            tfdCodigoPro.requestFocus();
            return;
        }

        if (getEditandoItem()) {
            modelItens.setRow(item, tblItens.getSelectedRow());
        } else {
            modelItens.addRow(item);
        }

        atualizaTabelaItens();

        setEditandoItem(false);
        limparDadosItem();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        setEditandoItem(false);

        if (tblItens.getSelectedRow() >= 0) {
            Itemvenda item = retornaItemSelecionado();

            // Atualiza objeto produto que será editado
            this.produto = item.getItemvendaPK().getProduto();

            tfdCodigoPro.setText(item.getItemvendaPK().getProduto().getCodigo());
            tfdProduto.setText(item.getItemvendaPK().getProduto().getDescricao());
            tfdPrecoUn.setText(item.getValor().setScale(2).toString());
            ffdQuantidade.setText(item.getQuantidade().toString());
            tfdDescontoUn.setText(item.getDesconto().setScale(2).toString());
            tfdSubtotal.setText(item.getValortotal().setScale(2).toString());

            setEditandoItem(true);

            tfdCodigoPro.requestFocus();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (tblItens.getSelectedRow() >= 0) {
            modelItens.removeRow(tblItens.getSelectedRow());
            atualizaTabelaItens();
            tblItens.requestFocus();
        }

        setEditandoItem(false);
        limparDadosItem();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void tfdCodigoProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdCodigoProFocusLost
        if (!tfdCodigoPro.getText().trim().isEmpty()) {

            // Se esta editando o item, não carrega os dados do cadsatro
            if (editandoItem
                    && tfdCodigoPro.getText().equals(retornaItemSelecionado().getItemvendaPK().getProduto().getCodigo())) {
                return;
            }

            ArrayList<Produto> produtos = new GenericDAO().consultarComCriterio("Produto", "codigo", tfdCodigoPro.getText());

            if (produtos.size() > 0) {
                // Considera o primeiro produto encontrado
                this.produto = produtos.get(0);
                atualizaInputProduto(this.produto);
            }
        }
    }//GEN-LAST:event_tfdCodigoProFocusLost

    private void atualizaInputProduto(Produto produto) {
        tfdProduto.setText(produto.getDescricao());
        tfdPrecoUn.setText(produto.getValorvenda().setScale(2).toString());
        atualizaSubtotal();
    }

    private void setEditandoItem(boolean editando) {
        editandoItem = editando;
    }

    private boolean getEditandoItem() {
        return editandoItem;
    }

    private void limparDadosItem() {
        tfdCodigoPro.setText("");
        tfdProduto.setText("");
        tfdPrecoUn.setText("");
        ffdQuantidade.setText("");
        tfdDescontoUn.setText("");
        tfdSubtotal.setText("");
    }

    private Itemvenda retornaItemSelecionado() {
        Itemvenda item = new Itemvenda();

        if (tblItens.getSelectedRow() >= 0) {
            item = modelItens.get(tblItens.getSelectedRow());
        }

        return item;
    }

    private void atualizaTabelaItens() {
        tblItens.setModel(modelItens);
        atualizaTotal();
    }

    private void atualizaSubtotal() {
        try {
            BigDecimal qtd = Formatacao.converteStringParaBigDecimal(ffdQuantidade.getText());
            BigDecimal desc = tfdDescontoUn.getValue();
            BigDecimal preco = tfdPrecoUn.getValue();

            BigDecimal sub = BigDecimal.ZERO;

            if (qtd.intValue() > 0) {
                preco = preco.subtract(desc);
                sub = preco.multiply(qtd);
            }

            tfdSubtotal.setText(sub.setScale(2).toString());
        } catch (Exception e) {
        }
    }

    private void atualizaTotal() {
        BigDecimal total = BigDecimal.ZERO;

        total = getTotal();
        lblTotal.setText("Total R$ " + total.setScale(2, RoundingMode.HALF_DOWN));

        total = getTotalLiquido();
        lblTotalLiquido.setText("Total Líquido R$ " + total.setScale(2, RoundingMode.HALF_DOWN));
    }

    private BigDecimal getTotal() {
        BigDecimal total = BigDecimal.ZERO;

        if (modelItens.getRowCount() > 0) {
            for (int i = 0; i < modelItens.getRowCount(); i++) {
                total = total.add(modelItens.get(i).getValortotal());
            }
        }

        return total;
    }

    private BigDecimal getTotalLiquido() {
        BigDecimal total = getTotal();

        if (tfdDesconto.getValue().intValue() > 0) {
            total = total.subtract(tfdDesconto.getValue());
        }

        return total;
    }

    private void ffdQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ffdQuantidadeFocusLost
        atualizaSubtotal();
    }//GEN-LAST:event_ffdQuantidadeFocusLost

    private void tfdDescontoUnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdDescontoUnFocusLost
        atualizaSubtotal();
    }//GEN-LAST:event_tfdDescontoUnFocusLost

    private boolean validaItens() {
        boolean inputOK = true;

        for (int i = 0; i < modelItens.getRowCount(); i++) {

            if (!validaItem(modelItens.get(i))) {
                inputOK = false;
                break;
            }

            // Valida produtos duplicados
            for (int j = 0; j < modelItens.getRowCount(); j++) {
                if (i != j) {
                    if (modelItens.get(i).getItemvendaPK().getProduto().getId() == modelItens.get(j).getItemvendaPK().getProduto().getId()) {
                        Mensagem.mostraAletra("Atenção", "Produto informado mais de uma vez \n Produto: " + modelItens.get(i).getItemvendaPK().getProduto().getCodigo());
                        inputOK = false;
                        break;
                    }
                }
            }

            if (!inputOK) {
                break;
            }
        }

        return inputOK;
    }

    private boolean validaItem(Itemvenda item) {
        boolean inputOK = true;

        while (inputOK) {
            // Valida quantidade
            if (item.getQuantidade() == null || item.getQuantidade().doubleValue() <= 0) {
                Mensagem.mostraAletra("Atenção", "Informe uma quantidade válida \n Produto: " + item.getItemvendaPK().getProduto().getCodigo());
                inputOK = false;
                break;
            }

            // Valida o desconto
            if (item.getDesconto().doubleValue() > item.getValor().doubleValue()) {
                Mensagem.mostraAletra("Atenção", "Desconto do produto inválido \n Produto: " + item.getItemvendaPK().getProduto().getCodigo());
                inputOK = false;
                break;
            }

            // Valida valor
            if (item.getValortotal().doubleValue() < 0) {
                Mensagem.mostraAletra("Atenção", "Valor do produto inválido \n Produto: " + item.getItemvendaPK().getProduto().getCodigo());
                inputOK = false;
                break;
            }

            break;
        }

        return inputOK;
    }

    private boolean validaPedido() {
        boolean inputOK = true;

        while (inputOK) {
            if (modelItens.getRowCount() == 0) {
                Mensagem.mostraAletra("Atenção", "Informe os itens da venda");
                inputOK = false;
                break;
            }

            if (getTotalLiquido().doubleValue() < 0) {
                Mensagem.mostraAletra("Atenção", "Valor do pedido inválido");
                inputOK = false;
                break;
            }

            boolean itensValidos = validaItens();

            if (!itensValidos) {
                inputOK = false;
                break;
            }

            break;
        }

        return inputOK;
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        JComponent[] components = new JComponent[]{cbmStatus, tfdCliente, tfdVendedor};
        VerificadorCampos verifier = new VerificadorCampos(components);

        if (!verifier.validaCampos()) {
            return;
        }

        if (!validaPedido()) {
            return;
        }

        this.dao = new GenericDAO<>();

        // Dados da venda
        if (getEditandoVenda()) {
            venda.setPago(venda.getPago());
        } else {
            this.venda = new Venda();
            venda.setDia(new java.util.Date());
            venda.setHora(new java.util.Date());
            venda.setPago(false);
        }

        if (dlgClientes.getCliente() != null) {
            venda.setCliente(dlgClientes.getCliente());
        }

        if (dlgColaboradores.getColaborador() != null) {
            venda.setVendedor(dlgColaboradores.getColaborador());
        }

        venda.setStatus(Venda.getStatusPelaDescricao(cbmStatus.getSelectedItem().toString()));
        venda.setFormapagamento(new Formapagamento(1));
        venda.setValor(getTotal());
        venda.setValortotal(getTotalLiquido());
        venda.setDesconto(tfdDesconto.getValue().setScale(2));
        venda.setDescricaodesconto(tfdDescrDesc.getText());
        venda.setObservacao(tfdObservacao.getText());

        if (getEditandoVenda()) {
            venda.removeAllItemvenda();
        }

        // Itens da venda
        for (Itemvenda item : modelItens.getItens()) {
            // Atualiza a venda
            ItemvendaPK pk = new ItemvendaPK(item.getItemvendaPK().getProduto(), venda);
            item.setItemvendaPK(pk);
            // Adiciona aos itens
            venda.addItemvenda(item);
        }

        try {
            if (getEditandoVenda()) {
                if (!dao.atualizar(venda)) {
                    throw new Exception("Erro ao atualizar venda");
                }
            } else {
                if (!dao.salvar(venda)) {
                    throw new Exception("Erro ao salvar venda");
                }
            }

            Mensagem.mostraInformacao("Sucesso", "Venda " + ((getEditandoVenda()) ? "atualizada" : "salva") + " com sucesso");
            limparPainelCadastro();

        } catch (Exception e) {
            Mensagem.mostraErro("Problema", "Problema ao " + ((getEditandoVenda()) ? "atualizar" : "salvar") + " venda");
            logger.error("Erro ao atualizar tabelas", e);
        }

        focus();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Pega o código do registro para consultar o objeto
        int id = Integer.parseInt(tblVendas.getValueAt(tblVendas.getSelectedRow(), 0).toString());
        this.venda = dao.consultarPorId(id, "Venda");

        //Abre uma mensagem pedindo se o usuário realmente quer excluír o registro
        boolean resposta = Mensagem.confirmaMensagem("Atenção", "Deseja realmente cancelar a venda: " + venda.getId() + "?");

        if (resposta) {
            // Atualiza a venda para Cancelada
            venda.setStatus(Venda.STATUS_CANCELADA);

            if (dao.atualizar(venda)) {
                Mensagem.mostraInformacao("Confirmação de exclusão", "Venda cancelada");

                this.vendas = dao.consultarTodos("Venda");
                this.modelVenda = new jtmVenda(vendas);
                this.tblVendas.setModel(modelVenda);
            } else {
                Mensagem.mostraErro("Problema", "Problema para cancelar venda");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Pega o código do registro para consultar o objeto
        int id = Integer.parseInt(tblVendas.getValueAt(tblVendas.getSelectedRow(), 0).toString());
        this.venda = dao.consultarPorId(id, "Venda");

        limparPainelCadastro();

        // Pega os dados se existir objeto
        if (this.venda != null) {
            tfdVenda.setText(venda.getId().toString());
            ffdData.setValue(venda.getDia());
            cbmStatus.setSelectedItem(Venda.getDescricaoStatus(venda.getStatus()));

            rbtPagaSim.setSelected(venda.getPago());
            rbtPagaNao.setSelected(!venda.getPago());

            String cliente;
            if (venda.getCliente().getCnpj() != null) {
                cliente = venda.getCliente().getCnpj();
            } else {
                cliente = venda.getCliente().getCpf();
            }
            cliente = cliente + " - " + venda.getCliente().getNome();
            tfdCliente.setText(cliente);

            tfdVendedor.setText(venda.getVendedor().getNomecompleto());
            tfdDesconto.setValue(venda.getDesconto());
            tfdDescrDesc.setText(venda.getDescricaodesconto());
            tfdObservacao.setText(venda.getObservacao());

            // Itens
            ArrayList<Itemvenda> itens = new ArrayList();
            for (Itemvenda item : venda.getItemvendaCollection()) {
                itens.add(item);
            }
            this.modelItens = new jtmItensVenda(itens);
            tblItens.setModel(this.modelItens);

            atualizaSubtotal();
            atualizaTotal();

            tabAbas.setSelectedIndex(0);
            setEditandoVenda(true);
            focus();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        dao = new GenericDAO();
        vendas = new ArrayList();

        vendas = dao.consultarTodos("Venda");
        tblVendas.setModel(new jtmVenda(vendas));
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tfdDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdDescontoFocusLost
        atualizaTotal();
    }//GEN-LAST:event_tfdDescontoFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnPagamento;
    private javax.swing.ButtonGroup btgPaga;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnZoom;
    private javax.swing.JButton btnZoomCliente;
    private javax.swing.JButton btnZoomVendedor;
    private javax.swing.JComboBox<String> cbmStatus;
    private javax.swing.JFormattedTextField ffdData;
    private javax.swing.JFormattedTextField ffdQuantidade;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private de.javasoft.swing.JYTableScrollPane jYTableScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalLiquido;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlComplemento;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JPanel pnlItens;
    private javax.swing.JRadioButton rbtPagaNao;
    private javax.swing.JRadioButton rbtPagaSim;
    private javax.swing.JTabbedPane tabAbas;
    private javax.swing.JTable tblItens;
    private de.javasoft.swing.JYTable tblVendas;
    private javax.swing.JTable tblVendasE;
    private javax.swing.JTextField tfdCliente;
    private javax.swing.JTextField tfdCodigoPro;
    private apoio.MoedaFormatada tfdDesconto;
    private apoio.MoedaFormatada tfdDescontoUn;
    private javax.swing.JTextField tfdDescrDesc;
    private javax.swing.JTextField tfdObservacao;
    private apoio.MoedaFormatada tfdPrecoUn;
    private javax.swing.JTextField tfdProduto;
    private apoio.MoedaFormatada tfdSubtotal;
    private javax.swing.JTextField tfdVenda;
    private javax.swing.JTextField tfdVendedor;
    // End of variables declaration//GEN-END:variables
}
