/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.ColoreCampos;
import apoio.Mensagem;
import apoio.VerificadorCampos;
import dao.GenericDAO;
import entidade.Config;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import static telas.FrmPrincipal.config;

/**
 *
 * @author Morgana
 */
public class IfrmConfiguracoes extends javax.swing.JInternalFrame {

    private Config config;
    GenericDAO<Config> dao;

    public IfrmConfiguracoes(Config config) {

        this.config = config;
        initComponents();
        if (this.config.getAuditorialigada()) {
            rbtLigada.setSelected(true);
        } else {
            rbtDesligada.setSelected(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        tabAbas = new javax.swing.JTabbedPane();
        pnlCadastro = new javax.swing.JPanel();
        lblAuditoria = new javax.swing.JLabel();
        rbtLigada = new javax.swing.JRadioButton();
        rbtDesligada = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Configurações do Sistema");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tabAbas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabAbasStateChanged(evt);
            }
        });
        tabAbas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tabAbasFocusLost(evt);
            }
        });

        pnlCadastro.setName("pnlCadastro"); // NOI18N

        lblAuditoria.setText("Auditoria *");

        rbtLigada.setText("Ligada");
        rbtLigada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtLigadaItemStateChanged(evt);
            }
        });
        rbtLigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtLigadaActionPerformed(evt);
            }
        });

        rbtDesligada.setText("Desligada");
        rbtDesligada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtDesligadaItemStateChanged(evt);
            }
        });
        rbtDesligada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDesligadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtLigada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtDesligada)
                .addContainerGap(674, Short.MAX_VALUE))
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtLigada)
                    .addComponent(rbtDesligada)
                    .addComponent(lblAuditoria))
                .addContainerGap(407, Short.MAX_VALUE))
        );

        tabAbas.addTab("Geral", pnlCadastro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(tabAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        tabAbas.getAccessibleContext().setAccessibleName("Auditoria");

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabAbasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabAbasFocusLost

    }//GEN-LAST:event_tabAbasFocusLost

    private void tabAbasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabAbasStateChanged

    }//GEN-LAST:event_tabAbasStateChanged

    private void rbtDesligadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDesligadaActionPerformed
        rbtLigada.setSelected(false);
    }//GEN-LAST:event_rbtDesligadaActionPerformed

    private void rbtDesligadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtDesligadaItemStateChanged

    }//GEN-LAST:event_rbtDesligadaItemStateChanged

    private void rbtLigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtLigadaActionPerformed
        rbtDesligada.setSelected(false);
    }//GEN-LAST:event_rbtLigadaActionPerformed

    private void rbtLigadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtLigadaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
        }
    }//GEN-LAST:event_rbtLigadaItemStateChanged

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (!validaCampos()) {
            return;
        }

        if (rbtLigada.isSelected()) {

            this.config.setAuditorialigada(true);

        } else {

            this.config.setAuditorialigada(false);

        }

        dao = new GenericDAO<>();

        if (!dao.atualizar(config)) {
            try {
                throw new Exception("Erro ao atualizar colaborador");
            } catch (Exception ex) {
                Logger.getLogger(IfrmConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

            Mensagem.mostraInformacao("Sucesso", "Configurações atualizadas com sucesso");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    private boolean validaCampos() {
        ArrayList<JComponent> components = new ArrayList();


        // Verifica se um radio foi selecionado, se não foi valida os dois
        if (!rbtLigada.isSelected() && !rbtDesligada.isSelected() ) {
            components.add(rbtLigada);
            components.add(rbtDesligada);
        } else {
            ColoreCampos.pintarCampo(rbtLigada, false);
            ColoreCampos.pintarCampo(rbtDesligada, false);
        }

        JComponent[] simpleArray = new JComponent[components.size()];
        components.toArray(simpleArray);
        VerificadorCampos verifier = new VerificadorCampos(simpleArray);

        if (!verifier.validaCampos()) {
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuditoria;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JRadioButton rbtDesligada;
    private javax.swing.JRadioButton rbtLigada;
    private javax.swing.JTabbedPane tabAbas;
    // End of variables declaration//GEN-END:variables
}
